name: CI

on:
  push:
    branches:
      - main
      - development
      - release/*
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest
    

  update-readme:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate function list
        run: |
          echo "Создаём README..."
          functions=$(grep -E '^def ' main.py | sed 's/def /- **/' | sed 's/:.*/**/')
          # создаём временный файл
          awk -v funcs="$functions" '{gsub(/\{\{ functions \}\}/, funcs)}1' README_template.md > README.md

      - name: Commit updated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README automatically"
          git push